Added remap config options
marcules/karma-remap-istanbul pull request #19
Opened 2016-08-05 00:28 UTC by oNaiPs

2016-08-25 13:20 UTC, nerumo commented
will this PR allow to exclude files from coverage?

2016-08-25 13:58 UTC, oNaiPs commented
Yes it will.

2016-08-27 02:26 UTC, erikbarke commented
This would be great to have!

2016-12-01 23:02 UTC, oNaiPs commented
Ping @delasteve

2016-12-05 18:12 UTC, mattlewis92 commented
@oNaiPs sorry about the late reply on this one, I kind of forgot I offered to help maintain this module until I saw your ping 😞  I've requested one small change then I'm happy to merge + release this 😄

2016-12-05 20:36 UTC, oNaiPs commented
@mattlewis92 thanks. I don't see any request?

2016-12-05 22:13 UTC, mateuszjuszkiewicz commented on README.md
> +    remapOptions: {} //additional remap options
Aren't you missing a comma at the end of this line (even though it's just a README)?

2016-12-05 22:48 UTC, mattlewis92 commented
@oNaiPs odd, I can't see it on my phone but I can on desktop. Does [this link](https://github.com/marcules/karma-remap-istanbul/pull/19/files/d3e47f183873d9a662dc8c28fd38bfd09e97a4fd) work for you?

2016-12-05 22:49 UTC, mattlewis92 requested changes

2016-12-05 22:49 UTC, mattlewis92 commented on index.js
> +    remapOptions.sources = sourceStore;
Can you change this to use [object.assign](https://www.npmjs.com/package/object.assign) so that the original remapOptions object isn't modified? Other than that LGTM.

2016-12-05 22:50 UTC, mattlewis92 commented
Oops, sorry I'm not used to githubs review feature, I didn't submit the review

2016-12-19 19:05 UTC, mattlewis92 commented
@oNaiPs would it be possible for you to rebase this PR on master so it can be merged?

2016-12-19 20:48 UTC, oNaiPs commented
Yes, I'll just make the changes you suggested and will push

2016-12-19 22:37 UTC, oNaiPs commented
@mattlewis92 should be ready. Let me know if it works for you.

2016-12-20 08:46 UTC, mattlewis92 approved these changes

2016-12-20 08:47 UTC, merged

2016-12-20 08:54 UTC, mattlewis92 commented
Perfect, thanks @oNaiPs ! Released as 0.3.0 😃