Supporting writeReport options
marcules/karma-remap-istanbul pull request #37
Opened 2017-02-02 19:04 UTC by zsoltvad

2017-02-02 19:14 UTC, mattlewis92 requested changes

2017-02-02 19:14 UTC, mattlewis92 commented on README.md
> +    writeReportOptions: {}, //additional writeReport options
Can you rename it from `writeReportOptions` to `reportOptions` as this is what remap-istanbul calls the arg in their docs: https://github.com/SitePen/remap-istanbul/blob/master/src/writeReport.js#L22

2017-02-02 19:14 UTC, mattlewis92 commented on package.json
> +  "version": "0.4.1",
Can you remove the version bump, as this is a feature it'll actually be 0.5.0

2017-02-02 19:15 UTC, mattlewis92 commented
Added a couple of minor changes, other than that LGTM!

2017-02-03 08:53 UTC, zsoltvad commented
Requested changes are fixed.

2017-02-03 10:16 UTC, mattlewis92 approved these changes

2017-02-03 10:17 UTC, merged

2017-02-03 10:17 UTC, mattlewis92 commented
Nice one, thanks!